/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import myPlugin from "strapi-plugin-workspace-plugin/strapi-admin";
import myplugin from "../../src/plugins/local-plugin/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.jsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  features: { future: {} },
  plugins: {
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    sentry: sentry,
    "users-permissions": usersPermissions,
    "my-plugin": myPlugin,
    myplugin: myplugin,
  },
});
